⚡Use `-mfloat-abi=hard`, Update `libm.a` and `libc.a` (#703)
* switch to hardware float and optimized libm

* fix hardware float flag

* switch -mfpu to original value

* use proper libm and libc

* use libc and libm from the right arch

* switch to softfp

* Update gcc toolchain to gcc13. And modify some compile flags

* build: :construction: add script to patch sdk headers

* build: :construction: update Makefile to call patch_headers

* remove experimental feature

* Add new libm

* build: :hammer: strip .ARM.attributes section from libv5rts.a

* fix spelling in patch_headers.py

* create patched include dir if it doesn't exist already

* add print statements to path_headers.py

* switch back to hard ABI

* patch sdk automatically in build script

* improve error handling in patch_headers.py

* exit if sdk is already patched

* delete patched sdk on clean build

* remove unnecessary debug message

* don't try to interact with libv5rts if not building PROS

* patch v5rts when for template target

* actually make `make template` patch the sdk

* use libc and libm used by Rocky

* fix undefined reference to _global_impure_ptr

* Update toolchain used for building to 13.3.rel1

* redo work on common.mk

* Revert "redo work on common.mk"

This reverts commit 5a72ab2987a5913b9f77db2a8b91aac597c722f7.

* restart work on make

* switch mfloat-abi to hard

* build: :construction: update Makefile to call patch_headers

* automatically patch sdk

* remove patched sdk on clean target

* Slightly modify makefiles. Everything working. Just fixing some minor typos and print infos

* exit with error on all exceptions in patch_headers.py

* Revert "exit with error on all exceptions in patch_headers.py"

This reverts commit abd9d1b82da0de33e349a7ae8dc47af027cda442.

---------

Co-authored-by: Rocky14683 <rocky10208@gmail.com>
Co-authored-by: ion098 <146852218+ion098@users.noreply.github.com>
Co-authored-by: Andrew Lu <lu987@purdue.edu>